### ISSUE TITLE
Strange autocomplete

### ISSUE THREAD

**Issue by littlewhitecloud** [billyeatcookies/cupcake#29]
https://github.com/billyeatcookies/cupcake/assets/71159641/e04f532b-d321-44bc-bbb7-b365f87a4cab

First, autocomplete will insert the word, not really complete the word that user input.
Second, when I input "{" it will complete a "]" for some reason.

**Comment by billyeatcookies** [comment]
@littlewhitecloud eyy thanks for opening the issue on this! I can see that the entire editor is messed up right now. I haven't updated the repo to include the changes made in the main project. Cupcake is basically extracted from the main project to work as a standalone thing. I will work on updating the editor. 

You can check the main project for further info on fixes made to autocomplete: https://github.com/billyeatcookies/biscuit

**Comment by littlewhitecloud** [comment]
Thank you for checking out this issues, I will check that repo. This is a wonderful project!

**Comment by Moosems** [comment]
Nice project idea :). I like how you went about doing it.

**Comment by billyeatcookies** [comment]
@Moosems thank you! ❤️ I will be updating the repo to include all fixes :)

**Comment by Moosems** [comment]
A suggestion idea: you could try using pygments for the syntax highlighting :).

**Comment by billyeatcookies** [comment]
@Moosems exactly, pygments was used for syntax highlighting in the updated version! xd
https://github.com/billyeatcookies/Biscuit/blob/main/biscuit/core/components/editors/texteditor/highlighter.py

**Comment by billyeatcookies** [comment]
@littlewhitecloud fixed in https://github.com/billyeatcookies/cupcake/releases/tag/v0.25.5
