### ISSUE TITLE
More language support

### ISSUE THREAD

**Issue by arnav56745** [billyeatcookies/cupcake#30]
I want more language support but only C++ and Plain text is supported. I also want Python support.

**Comment by billyeatcookies** [comment]
@arnav56745 thanks for opening the issue on this! ❤ The features have already been added to the editor, haven't updated this repo yet. Cupcake is basically extracted from the main project to work as a standalone thing. I will work on updating the source code! 

You can check the main project here: https://github.com/billyeatcookies/biscuit

**Comment by billyeatcookies** [comment]
@Moosems to make the process simple, using treesitter or textmate grammar files would be great! although I have tried to integrate treesitter before, I failed to get it working right

**Comment by Moosems** [comment]
I personally don't see the major advantage of using tree sitter. It doesn't support that many languages and if performance is a concern then only highlighting visible areas and reducing what you lex is much better overall.

**Comment by billyeatcookies** [comment]
@Moosems apart from the highlights done by pygments, I'm also working on LSP client to do semantic syntax highlights.

Also, yet another issue occurs when I tried to highlight the visible areas. For example, following python code
```
"""
imagine this docstring is a too long, and the user scrolled up to a point where the quote group is not visible anymore.
...


the lexer would take in the lines from here, and it would parse the rest as docstring!
"""

**Comment by arnav56745** [comment]
@billyeatcookies Where will the cupcake editor be in "https://github.com/billyeatcookies/Biscuit/"?

**Comment by billyeatcookies** [comment]
@arnav56745 You won't be able to use the code directly without some minor modifications :) I would also love to receive any help with the process! ❤️ 
https://github.com/billyeatcookies/Biscuit/tree/main/biscuit/core/components/editors/texteditor

**Comment by Moosems** [comment]
Ahh the multi line docstring/comment (MLCDS as I call it in my personal project). Yes, those absolutely pose an issue. The way I am planning to solve them is highlight the visible area once and, if the tag is found anywhere (keep a persistent memory to look at unhighlighted areas), figure out what created it and if it appears anywhere else in the file.  If there are no other that means the end is either in the visible area and is working properly or it is past the visible area and is also working properly. The issue is when the start and end are the same so make pairs and if there's an odd number in the visible area add an end/start tag in the proper place to where the other end of the pair is such that you get the proper highlighting. If that didn't make sense, yeah, there's a lot of stuff going on 😅.

**Comment by Moosems** [comment]
There's not really any good way to handle them.

**Comment by billyeatcookies** [comment]
@Moosems I'm thinking the project you mentioned is chlorophyll? I have checked it before, the issue I faced with using the lib directly was that I was not able to modify the proxy set up within chlorophyll 😅 

and yes, that's a lot of logic to comprehend, but I've somewhat got the idea xd

**Comment by Moosems** [comment]
Yeah I have been working eight chlorophyll for some time now and enjoy using it.

**Comment by billyeatcookies** [comment]
@Moosems I have found and I'm currently going through your pr on this! :) https://github.com/rdbende/chlorophyll/pull/35

**Comment by Moosems** [comment]
Yeah, I've started by first just getting it to highlight what's visible and now will work on adding MLCDS.

**Comment by arnav56745** [comment]
@billyeatcookies Are you currently working? I am waiting for new update

**Comment by billyeatcookies** [comment]
@arnav56745 yes, see pr https://github.com/billyeatcookies/cupcake/pull/31

**Comment by billyeatcookies** [comment]
@arnav56745 this issue has been considered in new release https://github.com/billyeatcookies/cupcake/releases/tag/v0.25.5

**Comment by arnav56745** [comment]
Thanks! ❤🙂

**Comment by billyeatcookies** [comment]
@arnav56745 the readme has been updated to include further good docs on integrating the editor!

**Comment by arnav56745** [comment]
@billyeatcookies  I know!
