### ISSUE TITLE
Anyone else having issues with autocompletion

### ISSUE THREAD

**Issue by oreillysean** [billyeatcookies/cupcake#38]
Hi

Anyone else getting an issue with autocompletion, this is what I am getting.

https://github.com/billyeatcookies/cupcake/assets/1847902/b01dcfcd-a66e-4c4e-8e04-c575d1bc0c17

I have hacked together a fix and I am now getting this

https://github.com/billyeatcookies/cupcake/assets/1847902/38369723-d2de-4a65-86eb-e6cd8bc743a6

However maybe it is just an issue on my machine, so just checking if others are experiencing this.

**Comment by billyeatcookies** [comment]
@oreillysean thank you for opening the issue! I'm unable to reproduce this error in windows with the current version of cupcake, I highly doubt it's related to tkinter in mac os, which I have not tested before. I'd love to see how you were able to fix it if possible ❤

I can also notice the highlight for text widget on focus, which is not supposed to happen too.

**Comment by oreillysean** [comment]
Upon conducting tests on both Windows 11 and Debian Bookworm, I can confirm that they are operating as expected. Consequently, it appears that the issues I encountered likely stem from my machine which is a Mac running M2.

While I made an attempt to rectify the problem by developing a patch, the quality of my code was very poor. Moreover, considering that the root of the problem seems to lie with my personal hardware, it would no longer be necessary.

**Comment by billyeatcookies** [comment]
I would really like to get some debug reports on this, and figure out what's going on, currently, linux compatibility is done by @cid0rz, and mac is very not tested at all! If you can definitely share some good fixes you can think of too, would really love it :)
