### ISSUE TITLE
it dont work

### ISSUE THREAD

**Issue by ghost** [billyeatcookies/cupcake#4]
![iccpm79ek7w71](https://user-images.githubusercontent.com/104084860/164257615-d0f9732c-06e9-4640-9c85-37564e826da3.jpg)

**Comment by billyeatcookies** [comment]
works perfectly
![image](https://user-images.githubusercontent.com/70792552/164296485-1f009e64-9691-4311-9561-8add649f0f32.png)

**Comment by arnav56745** [comment]
Weird. Why in the world????

**Comment by billyeatcookies** [comment]
the fact that they're a ghost pretty much explains it lmao xd

**Comment by arnav56745** [comment]
they create botted accounts and they create issues (useless ones indeed) and after that, they delete the account. by the way, my explanation could be incorrect! still LOL!
